apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: mlops-proyecto3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: python:3.9-slim
        workingDir: /app
        command:
        - /bin/bash
        - -c
        - |
          pip install streamlit==1.28.1 requests pandas
          streamlit run app.py --server.port=8501 --server.address=0.0.0.0
        env:
        - name: FASTAPI_URL
          value: "http://fastapi:8000"
        - name: MLFLOW_URL
          value: "http://mlflow:5000"
        ports:
        - containerPort: 8501
        volumeMounts:
        - name: app-code
          mountPath: /app
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: app-code
        hostPath:
          path: /mnt/proyecto3_mlops/ui
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: mlops-proyecto3
spec:
  selector:
    app: streamlit
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30851
  type: NodePort
